#[derive(Debug)]
pub enum AddrMode {
    Imm,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndirectX,
    IndirectY,
    Implied,
    Relative,
    Accumulator,
}

#[derive(Debug)]
pub enum OCName {
    ADC, AND, ASL, BCC, BCS, BEQ, BIT, BMI, BNE, 
    BPL, BRK, BVC, BVS, CLC, CLD, CLI, CLV, CMP,
    CPX, CPY, DEC, DEX, DEY, EOR, INC, INX, INY,
    JMP, JSR, LDA, LDX, LDY, LSR, NOP, ORA, PHA,
    PHP, PLA, PLP, ROL, ROR, RTI, RTS, SBC, SEC, 
    SED, SEI, STA, STX, STY, TAX, TAY, TSX, TXA, 
    TXS, TYA,
}

#[derive(Debug)]
pub struct Opcode {
    hex: u8,
    pub name: OCName,
    pub mode: AddrMode,
    pub ncycles: u16
}


static OPCODES: [Opcode; 151] = [
    Opcode {hex: 0x69, name: OCName::ADC, mode: AddrMode::Imm, ncycles: 2},
    Opcode {hex: 0x65, name: OCName::ADC, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0x75, name: OCName::ADC, mode: AddrMode::ZeroPageX, ncycles: 4},
    Opcode {hex: 0x6D, name: OCName::ADC, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0x7D, name: OCName::ADC, mode: AddrMode::AbsoluteX, ncycles: 4},
    Opcode {hex: 0x79, name: OCName::ADC, mode: AddrMode::AbsoluteY, ncycles: 4},
    Opcode {hex: 0x61, name: OCName::ADC, mode: AddrMode::IndirectX, ncycles: 6},
    Opcode {hex: 0x71, name: OCName::ADC, mode: AddrMode::IndirectY, ncycles: 5},
    Opcode {hex: 0x29, name: OCName::AND, mode: AddrMode::Imm, ncycles: 2},
    Opcode {hex: 0x25, name: OCName::AND, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0x35, name: OCName::AND, mode: AddrMode::ZeroPageX, ncycles: 4},
    Opcode {hex: 0x2D, name: OCName::AND, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0x3D, name: OCName::AND, mode: AddrMode::AbsoluteX, ncycles: 4},
    Opcode {hex: 0x39, name: OCName::AND, mode: AddrMode::AbsoluteY, ncycles: 4},
    Opcode {hex: 0x21, name: OCName::AND, mode: AddrMode::IndirectX, ncycles: 6},
    Opcode {hex: 0x31, name: OCName::AND, mode: AddrMode::IndirectY, ncycles: 5},
    Opcode {hex: 0x0A, name: OCName::ASL, mode: AddrMode::Accumulator, ncycles: 2},
    Opcode {hex: 0x06, name: OCName::ASL, mode: AddrMode::ZeroPage,ncycles: 5},
    Opcode {hex: 0x16, name: OCName::ASL, mode: AddrMode::ZeroPageX, ncycles: 6},
    Opcode {hex: 0x0E, name: OCName::ASL, mode: AddrMode::Absolute, ncycles: 6},
    Opcode {hex: 0x1E, name: OCName::ASL, mode: AddrMode::AbsoluteX, ncycles: 7},
    Opcode {hex: 0x90, name: OCName::BCC, mode: AddrMode::Relative, ncycles: 2},
    Opcode {hex: 0xB0, name: OCName::BCS, mode: AddrMode::Relative, ncycles: 2},
    Opcode {hex: 0xF0, name: OCName::BEQ, mode: AddrMode::Relative, ncycles: 2},
    Opcode {hex: 0x24, name: OCName::BIT, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0x2C, name: OCName::BIT, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0x30, name: OCName::BMI, mode: AddrMode::Relative, ncycles: 2},
    Opcode {hex: 0xD0, name: OCName::BNE, mode: AddrMode::Relative, ncycles: 2},
    Opcode {hex: 0x10, name: OCName::BPL, mode: AddrMode::Relative, ncycles: 2},
    Opcode {hex: 0x00, name: OCName::BRK, mode: AddrMode::Implied, ncycles: 7},
    Opcode {hex: 0x50, name: OCName::BVC, mode: AddrMode::Relative, ncycles: 2},
    Opcode {hex: 0x70, name: OCName::BVS, mode: AddrMode::Relative, ncycles: 2},
    Opcode {hex: 0x18, name: OCName::CLC, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0xD8, name: OCName::CLD, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0x58, name: OCName::CLI, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0xB8, name: OCName::CLV, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0xC9, name: OCName::CMP, mode: AddrMode::Imm, ncycles: 2},
    Opcode {hex: 0xC5, name: OCName::CMP, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0xD5, name: OCName::CMP, mode: AddrMode::ZeroPageX, ncycles: 4},
    Opcode {hex: 0xCD, name: OCName::CMP, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0xDD, name: OCName::CMP, mode: AddrMode::AbsoluteX, ncycles: 4},
    Opcode {hex: 0xD9, name: OCName::CMP, mode: AddrMode::AbsoluteY, ncycles: 4},
    Opcode {hex: 0xC1, name: OCName::CMP, mode: AddrMode::IndirectX, ncycles: 6},
    Opcode {hex: 0xD1, name: OCName::CMP, mode: AddrMode::IndirectY, ncycles: 5},
    Opcode {hex: 0xE0, name: OCName::CPX, mode: AddrMode::Imm, ncycles: 2},
    Opcode {hex: 0xE4, name: OCName::CPX, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0xEC, name: OCName::CPX, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0xC0, name: OCName::CPY, mode: AddrMode::Imm, ncycles: 2},
    Opcode {hex: 0xC4, name: OCName::CPY, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0xCC, name: OCName::CPY, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0xC6, name: OCName::DEC, mode: AddrMode::ZeroPage, ncycles: 5},
    Opcode {hex: 0xD6, name: OCName::DEC, mode: AddrMode::ZeroPageX, ncycles: 6},
    Opcode {hex: 0xCE, name: OCName::DEC, mode: AddrMode::Absolute, ncycles: 6},
    Opcode {hex: 0xDE, name: OCName::DEC, mode: AddrMode::AbsoluteX, ncycles: 7},
    Opcode {hex: 0xCA, name: OCName::DEX, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0x88, name: OCName::DEY, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0x49, name: OCName::EOR, mode: AddrMode::Imm, ncycles: 2},
    Opcode {hex: 0x45, name: OCName::EOR, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0x55, name: OCName::EOR, mode: AddrMode::ZeroPageX, ncycles: 4},
    Opcode {hex: 0x4D, name: OCName::EOR, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0x5D, name: OCName::EOR, mode: AddrMode::AbsoluteX, ncycles: 4},
    Opcode {hex: 0x59, name: OCName::EOR, mode: AddrMode::AbsoluteY, ncycles: 4},
    Opcode {hex: 0x41, name: OCName::EOR, mode: AddrMode::IndirectX, ncycles: 6},
    Opcode {hex: 0x51, name: OCName::EOR, mode: AddrMode::IndirectY, ncycles: 5},
    Opcode {hex: 0xE6, name: OCName::INC, mode: AddrMode::ZeroPage, ncycles: 5},
    Opcode {hex: 0xF6, name: OCName::INC, mode: AddrMode::ZeroPageX, ncycles: 6},
    Opcode {hex: 0xEE, name: OCName::INC, mode: AddrMode::Absolute, ncycles: 6},
    Opcode {hex: 0xF6, name: OCName::INC, mode: AddrMode::AbsoluteX, ncycles: 7},
    Opcode {hex: 0xE8, name: OCName::INX, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0xC8, name: OCName::INY, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0x4C, name: OCName::JMP, mode: AddrMode::Absolute, ncycles: 3},
    Opcode {hex: 0x6C, name: OCName::JMP, mode: AddrMode::Indirect, ncycles: 5},
    Opcode {hex: 0x20, name: OCName::JSR, mode: AddrMode::Absolute, ncycles: 6},
    Opcode {hex: 0xA9, name: OCName::LDA, mode: AddrMode::Imm, ncycles: 2},
    Opcode {hex: 0xA5, name: OCName::LDA, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0xB5, name: OCName::LDA, mode: AddrMode::ZeroPageX, ncycles: 4},
    Opcode {hex: 0xAD, name: OCName::LDA, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0xBD, name: OCName::LDA, mode: AddrMode::AbsoluteX, ncycles: 4},
    Opcode {hex: 0xB9, name: OCName::LDA, mode: AddrMode::AbsoluteY, ncycles: 4},
    Opcode {hex: 0xA1, name: OCName::LDA, mode: AddrMode::IndirectX, ncycles: 6},
    Opcode {hex: 0xB1, name: OCName::LDA, mode: AddrMode::IndirectY, ncycles: 5},
    Opcode {hex: 0xA2, name: OCName::LDX, mode: AddrMode::Imm, ncycles: 2},
    Opcode {hex: 0xA6, name: OCName::LDX, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0xB6, name: OCName::LDX, mode: AddrMode::ZeroPageY, ncycles: 4},
    Opcode {hex: 0xAE, name: OCName::LDX, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0xBE, name: OCName::LDX, mode: AddrMode::AbsoluteY, ncycles: 4},
    Opcode {hex: 0xA0, name: OCName::LDY, mode: AddrMode::Imm, ncycles: 2},
    Opcode {hex: 0xA4, name: OCName::LDY, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0xB4, name: OCName::LDY, mode: AddrMode::ZeroPageX, ncycles: 4},
    Opcode {hex: 0xAC, name: OCName::LDY, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0xBC, name: OCName::LDY, mode: AddrMode::AbsoluteX, ncycles: 4},
    Opcode {hex: 0x4A, name: OCName::LSR, mode: AddrMode::Accumulator, ncycles: 2},
    Opcode {hex: 0x46, name: OCName::LSR, mode: AddrMode::ZeroPage, ncycles: 5},
    Opcode {hex: 0x56, name: OCName::LSR, mode: AddrMode::ZeroPageX, ncycles: 6},
    Opcode {hex: 0x4E, name: OCName::LSR, mode: AddrMode::Absolute, ncycles: 6},
    Opcode {hex: 0x5E, name: OCName::LSR, mode: AddrMode::AbsoluteX, ncycles: 7},
    Opcode {hex: 0xEA, name: OCName::NOP, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0x09, name: OCName::ORA, mode: AddrMode::Imm, ncycles: 2},
    Opcode {hex: 0x05, name: OCName::ORA, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0x15, name: OCName::ORA, mode: AddrMode::ZeroPageX, ncycles: 4},
    Opcode {hex: 0x0D, name: OCName::ORA, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0x1D, name: OCName::ORA, mode: AddrMode::AbsoluteX, ncycles: 4},
    Opcode {hex: 0x19, name: OCName::ORA, mode: AddrMode::AbsoluteY, ncycles: 4},
    Opcode {hex: 0x01, name: OCName::ORA, mode: AddrMode::IndirectX, ncycles: 6},
    Opcode {hex: 0x11, name: OCName::ORA, mode: AddrMode::IndirectY, ncycles: 5},
    Opcode {hex: 0x48, name: OCName::PHA, mode: AddrMode::Implied, ncycles: 3},
    Opcode {hex: 0x08, name: OCName::PHP, mode: AddrMode::Implied, ncycles: 3},
    Opcode {hex: 0x68, name: OCName::PLA, mode: AddrMode::Implied, ncycles: 4},
    Opcode {hex: 0x28, name: OCName::PLP, mode: AddrMode::Implied, ncycles: 4},
    Opcode {hex: 0x2A, name: OCName::ROL, mode: AddrMode::Accumulator, ncycles: 2},
    Opcode {hex: 0x2A, name: OCName::ROL, mode: AddrMode::ZeroPage, ncycles: 5},
    Opcode {hex: 0x26, name: OCName::ROL, mode: AddrMode::ZeroPageX, ncycles: 6},
    Opcode {hex: 0x36, name: OCName::ROL, mode: AddrMode::Absolute, ncycles: 6},
    Opcode {hex: 0x3E, name: OCName::ROL, mode: AddrMode::AbsoluteX, ncycles: 7},
    Opcode {hex: 0x6A, name: OCName::ROR, mode: AddrMode::Accumulator, ncycles: 2},
    Opcode {hex: 0x66, name: OCName::ROR, mode: AddrMode::ZeroPage, ncycles: 5},
    Opcode {hex: 0x76, name: OCName::ROR, mode: AddrMode::ZeroPageX, ncycles: 6},
    Opcode {hex: 0x6E, name: OCName::ROR, mode: AddrMode::Absolute, ncycles: 6},
    Opcode {hex: 0x7E, name: OCName::ROR, mode: AddrMode::AbsoluteX, ncycles: 7},
    Opcode {hex: 0x40, name: OCName::RTI, mode: AddrMode::Implied, ncycles: 6},
    Opcode {hex: 0x60, name: OCName::RTS, mode: AddrMode::Implied, ncycles: 6},
    Opcode {hex: 0xE9, name: OCName::SBC, mode: AddrMode::Imm, ncycles: 2},
    Opcode {hex: 0xE5, name: OCName::SBC, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0xF5, name: OCName::SBC, mode: AddrMode::ZeroPageX, ncycles: 4},
    Opcode {hex: 0xED, name: OCName::SBC, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0xFD, name: OCName::SBC, mode: AddrMode::AbsoluteX, ncycles: 4},
    Opcode {hex: 0xF9, name: OCName::SBC, mode: AddrMode::AbsoluteY, ncycles: 4},
    Opcode {hex: 0xE1, name: OCName::SBC, mode: AddrMode::IndirectX, ncycles: 6},
    Opcode {hex: 0xF1, name: OCName::SBC, mode: AddrMode::IndirectY, ncycles: 5},
    Opcode {hex: 0x38, name: OCName::SEC, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0xF8, name: OCName::SED, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0x78, name: OCName::SEI, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0x85, name: OCName::STA, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0x95, name: OCName::STA, mode: AddrMode::ZeroPageX, ncycles: 4},
    Opcode {hex: 0x8D, name: OCName::STA, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0x9D, name: OCName::STA, mode: AddrMode::AbsoluteX, ncycles: 5},
    Opcode {hex: 0x99, name: OCName::STA, mode: AddrMode::AbsoluteY, ncycles: 5},
    Opcode {hex: 0x81, name: OCName::STA, mode: AddrMode::IndirectX, ncycles: 6},
    Opcode {hex: 0x91, name: OCName::STA, mode: AddrMode::IndirectY, ncycles: 6},
    Opcode {hex: 0x86, name: OCName::STX, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0x96, name: OCName::STX, mode: AddrMode::ZeroPageY, ncycles: 4},
    Opcode {hex: 0x8E, name: OCName::STX, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0x84, name: OCName::STY, mode: AddrMode::ZeroPage, ncycles: 3},
    Opcode {hex: 0x94, name: OCName::STY, mode: AddrMode::ZeroPageY, ncycles: 4},
    Opcode {hex: 0x8C, name: OCName::STY, mode: AddrMode::Absolute, ncycles: 4},
    Opcode {hex: 0xAA, name: OCName::TAX, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0xA8, name: OCName::TAY, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0xBA, name: OCName::TSX, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0x8A, name: OCName::TXA, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0x9A, name: OCName::TXS, mode: AddrMode::Implied, ncycles: 2},
    Opcode {hex: 0x98, name: OCName::TYA, mode: AddrMode::Implied, ncycles: 2},
];

pub fn opcode_lookup(hex: u8) -> Option<&'static Opcode> {
        OPCODES.iter().filter(|op| op.hex == hex).next()
}


